// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.6.1
// source: app/proto/pipes.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pipe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Pipe) Reset() {
	*x = Pipe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_pipes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipe) ProtoMessage() {}

func (x *Pipe) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_pipes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipe.ProtoReflect.Descriptor instead.
func (*Pipe) Descriptor() ([]byte, []int) {
	return file_app_proto_pipes_proto_rawDescGZIP(), []int{0}
}

func (x *Pipe) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_app_proto_pipes_proto protoreflect.FileDescriptor

var file_app_proto_pipes_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x69, 0x70, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x70, 0x70, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x22, 0x1c, 0x0a, 0x04, 0x50, 0x69, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42,
	0x0b, 0x5a, 0x09, 0x61, 0x70, 0x70, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_proto_pipes_proto_rawDescOnce sync.Once
	file_app_proto_pipes_proto_rawDescData = file_app_proto_pipes_proto_rawDesc
)

func file_app_proto_pipes_proto_rawDescGZIP() []byte {
	file_app_proto_pipes_proto_rawDescOnce.Do(func() {
		file_app_proto_pipes_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_proto_pipes_proto_rawDescData)
	})
	return file_app_proto_pipes_proto_rawDescData
}

var file_app_proto_pipes_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_proto_pipes_proto_goTypes = []interface{}{
	(*Pipe)(nil), // 0: appTypes.Pipe
}
var file_app_proto_pipes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_proto_pipes_proto_init() }
func file_app_proto_pipes_proto_init() {
	if File_app_proto_pipes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_proto_pipes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pipe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_proto_pipes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_proto_pipes_proto_goTypes,
		DependencyIndexes: file_app_proto_pipes_proto_depIdxs,
		MessageInfos:      file_app_proto_pipes_proto_msgTypes,
	}.Build()
	File_app_proto_pipes_proto = out.File
	file_app_proto_pipes_proto_rawDesc = nil
	file_app_proto_pipes_proto_goTypes = nil
	file_app_proto_pipes_proto_depIdxs = nil
}
